### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by rosstex** [aykamko/hubot-piazza-slack#2]
Hubot works on its own, but I'm getting this error when attempting to install this package.

```
2016-06-14T21:21:33.765841+00:00` app[web.1]: [Tue Jun 14 2016 21:21:33 GMT+0000 (UTC)] ERROR Unable to load /app/node_modules/hubot-piazza-slack/src/piazza-slack: SyntaxError: Unexpected token )
2016-06-14T21:21:33.765853+00:00 app[web.1]:   at Module._compile (module.js:439:25)
2016-06-14T21:21:33.765854+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:474:10)
2016-06-14T21:21:33.765855+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2016-06-14T21:21:33.765856+00:00 app[web.1]:   at Function.Module._load (module.js:312:12)
2016-06-14T21:21:33.765856+00:00 app[web.1]:   at Module.require (module.js:364:17)
2016-06-14T21:21:33.765857+00:00 app[web.1]:   at require (module.js:380:17)
2016-06-14T21:21:33.765860+00:00 app[web.1]:   at createHtmlParser (/app/node_modules/to-markdown/lib/html-parser.js:32:17)
2016-06-14T21:21:33.765861+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/to-markdown/lib/html-parser.js:76:63)
2016-06-14T21:21:33.765861+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2016-06-14T21:21:33.765862+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:474:10)
2016-06-14T21:21:33.765863+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2016-06-14T21:21:33.765863+00:00 app[web.1]:   at Function.Module._load (module.js:312:12)
2016-06-14T21:21:33.765864+00:00 app[web.1]:   at Module.require (module.js:364:17)
2016-06-14T21:21:33.765865+00:00 app[web.1]:   at require (module.js:380:17)
2016-06-14T21:21:33.765865+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/to-markdown/index.js:15:18)
2016-06-14T21:21:33.765866+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2016-06-14T21:21:33.765867+00:00 app[web.1]:   at Object.Module._extensions..js (module.js:474:10)
2016-06-14T21:21:33.765867+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2016-06-14T21:21:33.765868+00:00 app[web.1]:   at Function.Module._load (module.js:312:12)
2016-06-14T21:21:33.765868+00:00 app[web.1]:   at Module.require (module.js:364:17)
2016-06-14T21:21:33.765869+00:00 app[web.1]:   at require (module.js:380:17)
2016-06-14T21:21:33.765870+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot-piazza-slack/src/lib/normalize.coffee:1:14, <js>:4:16)
2016-06-14T21:21:33.765871+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot-piazza-slack/src/lib/normalize.coffee:1:1, <js>:66:4)
2016-06-14T21:21:33.765871+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2016-06-14T21:21:33.765872+00:00 app[web.1]:   at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
2016-06-14T21:21:33.765873+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2016-06-14T21:21:33.765873+00:00 app[web.1]:   at Function.Module._load (module.js:312:12)
2016-06-14T21:21:33.765874+00:00 app[web.1]:   at Module.require (module.js:364:17)
2016-06-14T21:21:33.765875+00:00 app[web.1]:   at require (module.js:380:17)
2016-06-14T21:21:33.765876+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot-piazza-slack/src/piazza-slack.coffee:15:1, <js>:4:15)
2016-06-14T21:21:33.765876+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot-piazza-slack/src/piazza-slack.coffee:15:1, <js>:125:4)
2016-06-14T21:21:33.765877+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2016-06-14T21:21:33.765878+00:00 app[web.1]:   at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
2016-06-14T21:21:33.765878+00:00 app[web.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
2016-06-14T21:21:33.765879+00:00 app[web.1]:   at Function.Module._load (module.js:312:12)
2016-06-14T21:21:33.765879+00:00 app[web.1]:   at Module.require (module.js:364:17)
2016-06-14T21:21:33.765880+00:00 app[web.1]:   at require (module.js:380:17)
2016-06-14T21:21:33.765881+00:00 app[web.1]:   at Robot.loadFile (/app/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
2016-06-14T21:21:33.765881+00:00 app[web.1]:   at module.exports (/app/node_modules/hubot-piazza-slack/index.coffee:11:9, <js>:24:31)
2016-06-14T21:21:33.765882+00:00 app[web.1]:   at Robot.loadExternalScripts (/app/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
2016-06-14T21:21:33.765883+00:00 app[web.1]:   at /app/node_modules/hubot/bin/hubot:152:11, <js>:159:26
2016-06-14T21:21:33.765883+00:00 app[web.1]:   at fs.js:272:14
2016-06-14T21:21:33.765884+00:00 app[web.1]:   at Object.oncomplete (fs.js:108:15)
2016-06-14T21:21:33.765885+00:00 app[web.1]:
2016-06-14T21:21:34.863200+00:00 heroku[web.1]: Process exited with status 1
2016-06-14T21:21:34.886609+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by rosstex** [comment]
see #3
